#!/bin/bash
# Use this to make a new release version by creating a git tag and
# setting a matching VERSION string that will be compiled into the
# executable
#
# Usage:
#
#  >> ./make_version.sh v1.1.0
#

# Create the version file
echo "# << This file is automatically generated by make_version.sh >>" > version.h
echo "#ifndef VERSION" >> version.h
echo "#define VERSION  \"$1\"" >> version.h
echo "#endif" >> version.h

# Create the git tag
git tag -a "$1"

# Push the release to git
git push $1
